name-template: 'Release v$NEXT_PATCH_VERSION 🌈'
tag-template: '$NEXT_PATCH_VERSION'
branches: 'master'
categories:
  - title: '🚀 Features'
    labels:
      - 'action: new feature'
      - 'action: enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'action: bug'
      - 'action: bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore: documentation'
      - 'chore: refactor'
      - 'chore: dependencies'
exclude-labels:
  - 'skip-changelog'
  - 'action: release'
  - 'action: hot fix'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
