name: Draft Release

on:
  push:
    branches:
      - master
      - staging

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create draft release
        uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
